events { worker_connections 1024; }

http {
    # Proteksi: Maksimal 50 request per detik per IP
    limit_req_zone $binary_remote_addr zone=cimb_limit:10m rate=50r/s;

    upstream python_api {
        server api-service:8000;
    }

    server {
        listen 80;
        location / {
            limit_req zone=cimb_limit burst=20 nodelay;
            proxy_pass http://python_api;
        }
    }
}