events { worker_connections 1024; }

http {
    resolver 127.0.0.11 valid=10s;

    upstream python_api {
        least_conn;
        server capstone-cimb-api-service-1:8000;
        server capstone-cimb-api-service-2:8000;
        server capstone-cimb-api-service-3:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://python_api;
        }
    }
}
