global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cimb-api'
    static_configs:
      - targets: ['capstone-cimb-api-service-1:8000']
      - targets: ['capstone-cimb-api-service-2:8000']
      - targets: ['capstone-cimb-api-service-3:8000']
    
  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - cadvisor:8080