version: '3.8'

services:
  # 1. API Gateway (Nginx)
  api-gateway:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-service
    networks:
      - cimb-net

  # 2. Application Layer (Python API)
  api-service:
    build: ./services/api-python
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DB_URL=postgresql://admin:password@postgres:5432/cimb_db
    depends_on:
      - redis
      - postgres
    networks:
      - cimb-net

  # 3. Async Worker (Golang)
  worker-service:
    build: ./services/worker-golang
    environment:
      - REDIS_URL=redis:6379
      - DB_URL=postgres://admin:password@postgres:5432/cimb_db?sslmode=disable
    depends_on:
      - redis
      - postgres
    networks:
      - cimb-net

  # 4. Database & Cache
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cimb_db
    ports:
      - "5432:5432"
    networks:
      - cimb-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - cimb-net

  # 5. Monitoring
  prometheus:
    image: prom/prometheus
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - cimb-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - cimb-net

networks:
  cimb-net:
    driver: bridge